accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
     path('', views.welcome, name='welcome'),
     path('login/', views.login, name='login'),
     path('register/', views.register, name='register')
]

customusemodel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('accounts.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>

	<meta charset="utf-8">

</head>
<body>
	{% block content %}
	{% endblock content %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                    {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'account:register' %}">Sign Up Now</a>
            </small><br>
            <small class="text-muted">
                <a href="/">Forgot password?</a>
            </small>
        </div>
    </div>
{% endblock content %}

templates/register.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>

            By registering, you accept the <a color='#007bff'  href='/' target="_blank">Terms of Service</a> and <a color='#007bff'  href='/' target="_blank">Privacy Notice</a>

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'account:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}